# Generated by Django 5.2.8 on 2026-02-11 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0002_cliente_factura_itemfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_inventario.cliente'),
        ),
    ]
