# Generated by Django 5.1 on 2026-02-12 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0003_movimientoinventario_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_inventario.factura'),
        ),
    ]
